create view pembayaran_invoice as 
select 
pembayaran_customer.id_pembayaran, 
pembayaran_customer.id_refrensi,
pembayaran_customer.subject_pembayaran,
pembayaran_customer.tgl_bayar,
pembayaran_customer.attachment,
pembayaran_customer.notes_pembayaran,
pembayaran_customer.nominal_pembayaran,
pembayaran_customer.kurs_pembayaran,
pembayaran_customer.mata_uang_pembayaran,
pembayaran_customer.total_pembayaran,
pembayaran_customer.metode_pembayaran,
invoice_core.id_submit_invoice,
invoice_core.id_invoice,
invoice_core.bulan_invoice,
invoice_core.tahun_invoice,
invoice_core.no_invoice,
invoice_core.id_submit_oc,
invoice_core.id_submit_od,
invoice_core.nominal_pembayaran as nominal_invoice,
invoice_core.kurs_pembayaran as kurs_invoice,
invoice_core.mata_uang as mata_uang_invoice,
invoice_core.is_ppn,
invoice_core.ppn,
invoice_core.franco,
invoice_core.att,
invoice_core.alamat_penagihan,
invoice_core.tipe_invoice,
invoice_core.status_lunas,
invoice_core.status_aktif_invoice,
invoice_core.jatuh_tempo,
invoice_core.durasi_pembayaran,
invoice_core.no_rekening,
invoice_core.jumlah_box,
invoice_core.berat_bersih,
invoice_core.berat_kotor,
invoice_core.dimensi,
invoice_core.id_user_add,
invoice_core.tgl_invoice_add,
invoice_core.id_user_edit,
invoice_core.tgl_invoice_edit
from pembayaran_customer 
inner join invoice_core on invoice_core.id_submit_invoice = pembayaran_customer.id_refrensi;
