<link rel="stylesheet" href="<?php echo base_url();?>global/vendor/select2/select2.css">
<link rel="stylesheet" href="<?php echo base_url();?>global/vendor/bootstrap-tokenfield/bootstrap-tokenfield.css">
<link rel="stylesheet" href="<?php echo base_url();?>global/vendor/bootstrap-tagsinput/bootstrap-tagsinput.css">
<link rel="stylesheet" href="<?php echo base_url();?>global/vendor/bootstrap-select/bootstrap-select.css">
<link rel="stylesheet" href="<?php echo base_url();?>global/vendor/icheck/icheck.css">
<link rel="stylesheet" href="<?php echo base_url();?>global/vendor/switchery/switchery.css">
<link rel="stylesheet" href="<?php echo base_url();?>global/vendor/asrange/asRange.css">
<link rel="stylesheet" href="<?php echo base_url();?>global/vendor/ionrangeslider/ionrangeslider.min.css">
<link rel="stylesheet" href="<?php echo base_url();?>global/vendor/asspinner/asSpinner.css">
<link rel="stylesheet" href="<?php echo base_url();?>global/vendor/clockpicker/clockpicker.css">
<link rel="stylesheet" href="<?php echo base_url();?>global/vendor/ascolorpicker/asColorPicker.css">
<link rel="stylesheet" href="<?php echo base_url();?>global/vendor/bootstrap-touchspin/bootstrap-touchspin.css">
<link rel="stylesheet" href="<?php echo base_url();?>global/vendor/jquery-labelauty/jquery-labelauty.css">
<link rel="stylesheet" href="<?php echo base_url();?>global/vendor/bootstrap-datepicker/bootstrap-datepicker.css">
<link rel="stylesheet" href="<?php echo base_url();?>global/vendor/bootstrap-maxlength/bootstrap-maxlength.css">
<link rel="stylesheet" href="<?php echo base_url();?>global/vendor/timepicker/jquery-timepicker.css">
<link rel="stylesheet" href="<?php echo base_url();?>global/vendor/jquery-strength/jquery-strength.css">
<link rel="stylesheet" href="<?php echo base_url();?>global/vendor/multi-select/multi-select.css">
<link rel="stylesheet" href="<?php echo base_url();?>global/vendor/typeahead-js/typeahead.css">
<link rel="stylesheet" href="<?php echo base_url();?>assets/examples/css/forms/advanced.css">